---
- hosts: all
  become: true
  pre_tasks:

  - name: Installing Updates for Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "ubuntu"

- hosts: Controller
  become: true
  roles:
    - Horizon
    - Cinder
    - Neutron

- hosts: Computer
  become: true
  roles:
    - Horizon
    - Cinder
    - Neutron
